facebook/facebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facebook/user/urls.py
from django.contrib import admin
from django.urls import path
from .views import user_registration,user_login,user_info,searching,user_info_update,logout,search_info,update_profile_pic,interface



app_name = 'user'
urlpatterns = [
    path('',interface,name='interface'),
    path('registartion/',user_registration,name='registration'),
    path('login/',user_login,name='login',),
    path('info/',user_info,name='user-info'),
    path('search/',searching,name='search'),
    path('update/',user_info_update,name='update'),
    path('logout/',logout,name='logout'),
    path('search_info/<int:pk>/',search_info,name='search-info'),
    path('update_profile_pic/',update_profile_pic,name='update-profile-pic'),
]

facebook/user/models.py
from django.db import models

# Create your models here.
class User_signup(models.Model):
    #STATE_CHOICES = (
    #    (1,"Andra Pradesh"),
    #    (2,"Arunachal Pradesh"),
    #    (3,"Assam"),
    #    (4,"Bihar"),
    #    (5,"Chhattisgarh"),
    #    (6,"Goa"),
    #    (7,"Gujarat"),
    #    (8,"Haryana"),
    #    (9,"Himachal Pradesh"),
    #    (10,"Jammu and Kashmir"),
    #    (11,"Jharkhand"),
    #    (12,"Karnataka"),
    #    (13,"Kerala"),
    #    (14,"Madya Pradesh"),
    #    (15,"Maharashtra"),
    #    (16,"Manipur"),
    #    (17,"Meghalaya"),
    #    (18,"Mizoram"),
    #    (19,"Nagaland"),
    #    (20,"Orissa"),
    #    (21,"Punjab"),
    #    (22,"Rajasthan"),
    #    (23,"Sikkim"),
    #    (24,"Tamil Nadu"),
    #    (25,"Telagana"),
    #    (26,"Tripura"),
    #    (27,"Uttaranchal"),
    #    (28,"Uttar Pradesh"),
    #    (29,"West Bengal"),
#
    #)
    username = models.CharField(max_length=25,unique=True)
    password = models.CharField(max_length=25)
    cpassword = models.CharField(max_length=25)
    picture = models.ImageField(upload_to='profile_pic/',blank=True)
    fname = models.CharField(max_length=25)
    lname = models.CharField(max_length=25)
    dob = models.DateField()
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=20)
    #state = models.IntegerField(choices = STATE_CHOICES,default=1)

    def __str__(self):
        return self.username

facebook/user/forms.py
from django import forms
from .models import User_signup

class User_signup_form(forms.ModelForm):
    #STATE_CHOICES = (
    #    (1,"Andra Pradesh"),
    #    (2,"Arunachal Pradesh"),
    #    (3,"Assam"),
    #    (4,"Bihar"),
    #    (5,"Chhattisgarh"),
    #    (6,"Goa"),
    #    (7,"Gujarat"),
    #    (8,"Haryana"),
    #    (9,"Himachal Pradesh"),
    #    (10,"Jammu and Kashmir"),
    #    (11,"Jharkhand"),
    #    (12,"Karnataka"),
    #    (13,"Kerala"),
    #    (14,"Madya Pradesh"),
    #    (15,"Maharashtra"),
    #    (16,"Manipur"),
    #    (17,"Meghalaya"),
    #    (18,"Mizoram"),
    #    (19,"Nagaland"),
    #    (20,"Orissa"),
    #    (21,"Punjab"),
    #    (22,"Rajasthan"),
    #    (23,"Sikkim"),
    #    (24,"Tamil Nadu"),
    #    (25,"Telagana"),
    #    (26,"Tripura"),
    #    (27,"Uttaranchal"),
    #    (28,"Uttar Pradesh"),
    #    (29,"West Bengal"),
#
    #)

    username  = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'field','placeholder':'Username'}))
    password  = forms.CharField(label='',widget = forms.PasswordInput(attrs={'class':'field','placeholder':'Password'}))
    cpassword = forms.CharField(label='',widget = forms.PasswordInput(attrs={'class':'field','placeholder':'Confirm Password'}))
    picture   = forms.ImageField(label='Profile Pic',widget = forms.FileInput(attrs={'class':'image'}))
    fname     = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'field','placeholder':'First Name'}))
    lname     = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'field','placeholder':'Last Name'}))
    dob       = forms.DateField(label='DOB',widget=forms.SelectDateWidget(years=range(1990,2100),attrs={'class':'field','placeholder':'DOB'}))
    address   = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'field','placeholder':'Address'}))
   # state     = forms.ChoiceField(label='',choices = STATE_CHOICES,widget=forms.Select(attrs={'class':'field','placeholder':'State'}))
    city      = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'field','placeholder':'City'}))
    
    class Meta:
        model = User_signup
        fields = [
            'username',
            'password',
            'cpassword',
            'picture',
            'fname',
            'lname',
            'dob',
            'address',
            #'state',
            'city',
        ]
        
    def clean_cpassword(self):
        password = self.cleaned_data.get('password')
        cpassword = self.cleaned_data.get('cpassword')
        if password != cpassword:
            raise forms.ValidationError("Password and Confirm Password is not same")
        return cpassword

class User_login(forms.Form):
    username = forms.CharField(label='Username',widget=forms.TextInput(attrs={'class':'field'}))
    password = forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'field'}))

    class Meta:
        fields = [
            'username',
            'password',
        ]

class User_searching(forms.Form):
    name = forms.CharField(label='Name',required=False)

    class Meta:
        fields = [
            'name',
        ]
        


class Update_info(forms.ModelForm):
    
    fname     = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'field','placeholder':'First Name'}))
    lname     = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'field','placeholder':'Last Name'}))
    dob       = forms.DateField(label='',widget=forms.SelectDateWidget(years=range(1990,2100),attrs={'class':'field','placeholder':'DOB'}))
    address   = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'field','placeholder':'Address'}))
   
    city      = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'field','placeholder':'City'}))
    
    class Meta:
        model = User_signup
        fields = [
            
            'fname',
            'lname',
            'dob',
            'address',
            
            'city',
        ]

    
class Update_profile(forms.ModelForm):

    picture   = forms.ImageField(label='',required = False,widget = forms.FileInput(attrs={'class':'image','name':'pic'}))
        
    class Meta:
        model = User_signup
        fields = [
            'picture',
        ]

facebook/user/views.py
from django.shortcuts import render,redirect
from .forms import User_signup_form,User_login,User_searching,Update_info,Update_profile
from .models import User_signup

from django.db.models import Q
# Create your views here.

def user_registration(request,*args,**kwargs):
    form = User_signup_form(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save(commit = False)
            if 'profile_pic' in request.FILES:
                instance.picture = request.FILES['profile_pic']
            
            form.save()
            return redirect('user:interface')

    context = {'form':form}
    return render(request,'user/user_registration.html',context)


def user_login(request,*args,**kwargs):
    form = User_login(request.POST or None)
    username_not_available = False
    password_not_available = False
    if request.method == 'POST':
        
        data = request.POST.copy()
        username = data.get('username')
        password = data.get('password')
        print(password)

        try:
            user = User_signup.objects.get(username = username)
            print(user.password)
            if user.username == username and user.password == password:
                request.session['username'] = username
                return redirect('user:user-info')
            else:
                password_not_available = True
        except Exception:
            username_not_available = True

    context = {
        'form': form,
        'username_not_available': username_not_available,
        'password_not_available': password_not_available,
    }

    return render(request,'user/user_login.html',context)
def user_info(request,*args,**kwargs):
    if request.session.has_key('username'):
        username = request.session['username']

        try:
            user = User_signup.objects.get(username =username)
        except Exception:
            return redirect("user:login")


        context = {
            'user': user
        }

        return render(request,'user/user_info.html',context)
    else:
        return redirect('user:login')


def searching(request,*args,**kwargs):
    if request.session.has_key('username'):
        username = request.session['username']
        form = User_searching(request.POST or None)
        user = None
        if request.method == 'POST':
            data = request.POST.copy()
            name = data.get('name')
            if (' ' in name) == True:
                name = name.split(' ')
                print(name)
                print(name[0])
                fname = name[0]
                lname = name[1]
                user = User_signup.objects.filter(Q(fname__contains = fname) & Q(lname__contains = lname))
            else:
                fname = name 
                lname = ' '
                user = User_signup.objects.filter(Q(fname__contains = fname))

        context = {
            'user': user,
            'form': form,
        }
        return render(request,'user/search.html',context)
    else:
        return redirect('user:login')


def user_info_update(request,*args,**kwargs):
    if request.session.has_key('username'):
        username = request.session['username']

        try:
            user = User_signup.objects.get(username =username)
        except Exception:
            pass
        form = Update_info(request.POST or None)
        form.fields['fname'].initial = user.fname
        form.fields['dob'].initial = user.dob
        form.fields['lname'].initial = user.lname
        form.fields['address'].initial = user.address
        form.fields['city'].initial = user.city
        if request.method == 'POST':
            if form.is_valid():
                instance = form.save(commit = False)
                user.fname = instance.fname
                user.lname = instance.lname
                user.dob = instance.dob
                user.address = instance.address
                user.city = instance.city
                user.save()
                return redirect('user:user-info')
        context = {
            'form': form,
            'user': user,
        }
        return render(request,'user/update.html',context)
    else:
        return redirect("user:login")


def logout(request,*args,**kwargs):
    if request.session.has_key('username'):
        if request.method == 'POST':
            data = request.POST.copy()
            if data.get('Yes'):
                log = 'Yes'
                del request.session['username']
                return redirect('user:login')
            elif data.get('No'):
                log = 'No'
                return redirect('user:user-info')
            print(log)
            
           

    return render(request,'user/logout.html')


def search_info(request,pk,*args,**kwargs):
    if request.session.has_key('username'):
        user = User_signup.objects.get(pk=pk)
        context = {
            'user': user,
        }
        return render(request,'user/search_info.html',context)
    else:
        return redirect('user:login')

def update_profile_pic(request,*args,**kwargs):
    if request.session.has_key('username'):
        username = request.session['username']

        try:
            user = User_signup.objects.get(username =username)
        except Exception:
            pass
        form = Update_profile(request.POST or None, request.FILES or None)
        form.fields['picture'].initial = user.picture
        
        if request.method == 'POST':
            if form.is_valid():
                data = request.POST.copy()
                
                if data.get('submit'):
                    instance = form.save(commit = False)
                    if 'profile_pic' in request.FILES:
                        instance.picture = request.FILES['profile_pic']
                    user.picture = instance.picture
                    
                    user.save()
                    return redirect('user:user-info')
                elif data.get('cancel'):
                    return redirect('user:user-info')
        context = {
            'form': form,
            'user': user,
        }
        return render(request,'user/update_profile.html',context)
    else:
        return redirect("user:login")

def interface(request):
    return render(request,'user/interface.html')

facebook/user/templates/user/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>P-Facebook</title>
        <style>
            .navbar {
                    background-color: #333;
                    overflow: hidden;
                    margin-left:-8px;
                    position: fixed;
                    width: 100%;
                    }

                    /* Style the links inside the navigation bar */
            .navbar a {
                    float: left;
                    display: block;
                    color: #f2f2f2;
                    text-align: center;
                    padding: 14px 16px;
                    text-decoration: none;
                    font-size: 17px;
                    }

                    /* Change the color of links on hover */
            .navbar a:hover {
                    background-color: #ddd;
                    color: black;
                    }

                    /* Add a color to the active/current link */
            .navbar a.active {
                    background-color: #4CAF50;
                    color: white;
                    }
            .other {
                margin-top: 80px;
                position: absolute;
            }
        </style>
    </head>
    <body>
                <div class="navbar">
                    <a href="{% url 'user:search' %}" class='search'>Search</a>
                    <a href="{% url 'user:user-info' %}" class='info'>User Info</a>
                    <a href="{% url 'user:update' %}" class='update'>Update Info</a>
                    <a href="{% url 'user:logout' %}" class='logout'>Logout</a>
                </div>
                <div class="other">
                {% block content %}
                replace me
                {% endblock %}
            </div>
    </body>
</html>

facebook/user/templates/user/interface.html
<!DOCTYPE html>
<html>
    <head>
        <title>P-facebook</title>
        <style>
            
            div{
                margin-top:250px;
                margin-left:550px;
               
                border:3px solid black;
                border-radius:25px;
                width: 400px;
                padding: 20px;
                text-align:center;
                
            }
            .field{
                padding:7px 25px 7px 25px;
                margin-top:10px;
                margin-right:5px;
                margin-left:5px;
                margin-bottom:10px;
                border-radius:25px;
                border:2px solid;
               
                text-decoration:None;
                text-align:center;
            }
            
            
        </style>
    </head>
    <body>
        <form action='.' method="POST">{% csrf_token %}
            <div>
                <h1>Welcome To The P-Facebook</h1><br>
                <a class='field' href="{% url 'user:login' %}">Login</a>
                <a class='field' href="{% url 'user:registration' %}">Sign Up</a>
            </div>
        </form>
    </body>
</html>

facebook/user/templates/user/logout.html
{% extends 'user/base.html' %}
{% block content %}
<style>
        .logout{
                background-color:green;
        }
</style>
    <form action='.' method="POST">{% csrf_token %}
        <h1>Do you want to Logout?</h1>
        <input type='submit' value='Yes' name='Yes'>   <input type='submit' value='No' name='No'>
    
    </form>

{% endblock %}

facebook/user/templates/user/search.html
{% extends 'user/base.html' %}
{% block content %}
<style>
    .search{
            background-color:green;
    }
    .view{
            text-decoration:None;
            color:green;
            font-size:20px;
    }
</style>
<form action='.' method="POST">{% csrf_token %}
    <div class="search_it">
    <h1>Search</h1>
    {{ form.name }}
    <input type='submit' value='Submit'>
</div>
</form>
<br>
{% if user != None %}
{% for i in user %}
   <a class='view' href="{% url 'user:search-info' pk=i.pk %}" >{{ i.fname|title }}  {{ i.lname|title }}</a><br>
   ---------------------------<br>
{% endfor %}
{% endif %}
        
{% endblock %}

facebook/user/templates/user/search_info.html
{% extends 'user/base.html' %}
{% block content %}
   <h1 style="margin-left:100px;">Search Info</h1>
   <div style="position:absolute; margin-left:450px; font-size:35px; ">
           Username<br>
           Name<br>
           DOB<br>
           Address <br>
           City<br>
   </div>
   <div style="position:fixed; margin-left:630px; font-size:35px; font-style:oblique">
   : {{ user.username }}<br>
   : {{ user.fname }} {{ user.lname }}<br>
   : {{ user.dob }}<br>
   : {{ user.address }}<br>
   : {{ user.city }}<br>   
   </div>   
   <div style="margin-left:100px; position:absolute; text-align:center;">
   <img src="{{ user.picture.url }}"  heigth=270px width=270px  style=" 
                                             
                                             border:4px solid blue;
                                             " />
    </div>

            
{% endblock %}

facebook/user/templates/user/update.html
{% extends 'user/base.html' %}
{% block content %}
<style>
        .update{
                background-color:green;
        }
        .box{
                border:3px solid black;
                
                padding:20px 220px 60px 35px;
                border-radius:25px;
                
                
        }
        .field{
                padding:10px;
                text-align:center;
        }
        .the_info{
                position:absolute;
                font-size:35px;
                padding-top:5px;
                line-height: 56px;
                
        }
        .form{
                position:absolute;
                margin-left:190px;
                
        }
        .button{
                margin-top:310px;
                margin-left:150px;
        }
</style>

<form action='.' method='POST'>{% csrf_token %}
        <div class="box">
        
        <h1>Update Your Info</h1>
        <div class='the_info'">
                First Name -<br>
                Last Name - <br>
                DOB - <br>
                Address - <br>
                City -<br>
        </div>
        <div class='form'">
         {{ form.as_p }}
        </div>
        <input class='button' type='submit' value='submit'>
        </div>
</form>
        
{% endblock %}

facebook/user/templates/user/update_profile.html
{% extends 'user/base.html' %}
{% block content %}
    <form action='.' method='POST' enctype="multipart/form-data">{% csrf_token %}
        <h1 style="margin-left:50px;">Update Your Profile Pic</h1>
            <img src="{{ user.picture.url }}"  style="width: 40%; 
            float: right;
            border:3px solid blue;
            margin-right: 200px; 
            margin-top:00px;
            " />
        <div style="margin-left:50px;">
        {{ form.as_p }}
        
        <input type="submit" value='submit' name='submit'>
        <input type="submit" value='cancel' name='cancel'>
    </div>
    </form>
{% endblock %}

facebook/user/templates/user/user_info.html
{% extends 'user/base.html' %}
{% block content %}
        <style>
             .info{
                     background-color:green;
             }
        </style>
        <div style="position:absolute; margin-left:450px; font-size:35px; ">
                Username<br>
                Name<br>
                DOB<br>
                Address <br>
                City<br>
        </div>
        <div style="position:fixed; margin-left:630px; font-size:35px; font-style:oblique">
        : {{ user.username }}<br>
        : {{ user.fname }} {{ user.lname }}<br>
        : {{ user.dob }}<br>
        : {{ user.address }}<br>
        : {{ user.city }}<br>   
        </div>   
        <div style="margin-left:100px; position:absolute; text-align:center;">
        <img src="{{ user.picture.url }}"  heigth=270px width=270px  style=" 
                                                  
                                                  border:4px solid blue;
                                                  " />
        <a href='{% url "user:update-profile-pic" %}' style="margin-top:500px;">Update Profile Pic</a>
        </div> 
{% endblock %}

facebook/user/templates/user/user_login.html
<!DOCTYPE html>
<html>
    <head>
        <title>P-Facebook</title>
        <style>
            .field{
                padding:5px;

            }
            .box{
                width:400px;
                text-align:center;
                margin-top:200px;
                margin-left:570px;
                border:3px solid black;
                border-radius:25px;
                padding-bottom:30px;
            }
        </style>
    </head>
    <body>
        <div class='box'>
            <h1>Login</h1>
        <form action='.' method='POST'>{% csrf_token %}
            {% if username_not_available == True %}
            <h1>Username Is Incorrect</h1>
            {% elif password_not_available == True %}
            <h1>Password Is Incorrect</h1>
            {% endif %}
            {{ form.as_p }}
            <input type='submit' value='Login'>
        </form>
    </div>
    </body>
</html>

facebook/user/templates/user/user_registration.html
<!DOCTYPE html>
<html lang="en"> 
<head> 
    <title>P-Facebook</title>
    <meta charset="UTF-8"> 
    <style>
    .field{
        padding:5px;
    }
    .image{
        margin:10px;
    }
    .box{
        width:400px;
        margin-left:550px;
        margin-top:90px;
        padding-bottom:10px;
        border:3px solid black;
        border-radius:25px;
        text-align:center;
    }
    </style>
</head>
<body>
    <div class='box'>
    <h1>Registration</h1>
    <form action='.' method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{form.as_p}}
        <input type='submit' value='Submit'>
    </form>
</div>
</body>
</html>